name: Auth API status

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - uses: matt-ball/newman-action@master
        with:
          postmanApiKey: ${{ secrets.postmanApiKey }}
          collection: ${{ secrets.postmanAuthApiCollection }}
          environment: ${{ secrets.postmanAuthApiEnv }}
